### ISSUE TITLE
默认的镜像中，cuda是10.2版本的，能更新一版，兼容下30系的显卡吗

### ISSUE THREAD

**Issue by chenjian88888** [xtreme1-io/point-cloud-object-detection#5]

**Comment by Creating-ZXY** [comment]
您好，请问您解决了吗

**Comment by chenjian88888** [comment]
> 您好，请问您解决了吗

解决了，基础镜像dockerfile如下：

# 使用 CUDA 11.7.1 的基础镜像
FROM nvcr.io/nvidia/cuda:11.7.1-cudnn8-devel-ubuntu20.04

USER root
ENV DEBIAN_FRONTEND noninteractive

# 设置pip源为阿里云源
# ENV PIP_INDEX_URL=https://mirrors.aliyun.com/pypi/simple/
ENV PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple

# # 添加 NVIDIA apt 公钥
# RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub \
#     && apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/7fa2af80.pub

# 更新 apt 并安装基本工具
RUN apt-get clean && apt-get update \
    && apt-get install -y apt-utils ca-certificates git wget sudo vim net-tools 

# 安装 Python 及其依赖
# install python
RUN apt-get install -y libffi-dev libjpeg-dev zlib1g-dev libssl-dev python3-dev python3-pip \
    && ln -svf /usr/bin/python3 /usr/bin/python \
    && ln -svf /usr/bin/pip3 /usr/bin/pip \
    && pip install --upgrade pip

# 安装 PyTorch，指定适配 CUDA 11.7 的版本
# install PyTorch
RUN pip install Pillow==6.2

# # 将本地的 third_libs 目录复制到 Docker 镜像中的 /third_libs 目录
COPY ./third_libs /third_libs

RUN pip install /third_libs/torch-1.13.1+cu117-cp38-cp38-linux_x86_64.whl \
    && rm -rf /third_libs

RUN pip install torchvision==0.14.1+cu117 torchaudio==0.13.1 -f https://download.pytorch.org/whl/torch_stable.html

# install spconv
RUN pip install spconv-cu113

WORKDIR /app

# install pcdet
ENV TORCH_CUDA_ARCH_LIST="5.0 5.2 6.0 6.1 7.0 7.5 8.6+PTX"
# COPY . ./
COPY ./pcdet ./pcdet/
COPY ./requirements.txt ./
COPY ./setup.py ./
# 以下安装方式会有警告，先不管
RUN pip install -e .

**Comment by chenjian88888** [comment]
> 您好，请问您解决了吗

`解决了，看这个基础dockerfile，下面内容可能有高亮错误，对比原来的文件更新吧

# 使用 CUDA 11.7.1 的基础镜像
FROM nvcr.io/nvidia/cuda:11.7.1-cudnn8-devel-ubuntu20.04

USER root
ENV DEBIAN_FRONTEND noninteractive

# 设置pip源为阿里云源
# ENV PIP_INDEX_URL=https://mirrors.aliyun.com/pypi/simple/
ENV PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple

# # 添加 NVIDIA apt 公钥
# RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub \
#     && apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/7fa2af80.pub

# 更新 apt 并安装基本工具
RUN apt-get clean && apt-get update \
    && apt-get install -y apt-utils ca-certificates git wget sudo vim net-tools 

# 安装 Python 及其依赖
# install python
RUN apt-get install -y libffi-dev libjpeg-dev zlib1g-dev libssl-dev python3-dev python3-pip \
    && ln -svf /usr/bin/python3 /usr/bin/python \
    && ln -svf /usr/bin/pip3 /usr/bin/pip \
    && pip install --upgrade pip

# 安装 PyTorch，指定适配 CUDA 11.7 的版本
# install PyTorch
RUN pip install Pillow==6.2

# # 将本地的 third_libs 目录复制到 Docker 镜像中的 /third_libs 目录
COPY ./third_libs /third_libs

RUN pip install /third_libs/torch-1.13.1+cu117-cp38-cp38-linux_x86_64.whl \
    && rm -rf /third_libs

RUN pip install torchvision==0.14.1+cu117 torchaudio==0.13.1 -f https://download.pytorch.org/whl/torch_stable.html

# install spconv
RUN pip install spconv-cu113

WORKDIR /app

# install pcdet
ENV TORCH_CUDA_ARCH_LIST="5.0 5.2 6.0 6.1 7.0 7.5 8.6+PTX"
# COPY . ./
COPY ./pcdet ./pcdet/
COPY ./requirements.txt ./
COPY ./setup.py ./
# 以下安装方式会有警告，先不管
RUN pip install -e .

**Comment by Creating-ZXY** [comment]
`340.3 Installing collected packages: easydict, zipp, tqdm, setuptools, pyyaml, protobuf, pillow, packaging, numpy, networkx, llvmlite, tifffile, tensorboardX, SharedArray, scipy, PyWavelets, importlib-metadata, imageio, imagecodecs, scikit-image, numba, pcdet
351.2   DEPRECATION: Legacy editable install of pcdet==0.6.0+0 from file:///app (setup.py develop) is deprecated. pip 25.1 will enforce this behaviour
 change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not beha
ving as expected, try using --config-settings editable_mode=compat. Please consult the setuptools documentation for more information. Discussion can be found at https://github.com/pypa/pip/issues/11457
351.2   Running setup.py develop for pcdet
354.0     error: subprocess-exited-with-error
354.0
354.0     × python setup.py develop did not run successfully.
354.0     │ exit code: 1
354.0     ╰─> [90 lines of output]
354.0         running develop
354.0         running egg_info
354.0         creating pcdet.egg-info
354.0         writing pcdet.egg-info/PKG-INFO
354.0         writing dependency_links to pcdet.egg-info/dependency_links.txt
354.0         writing requirements to pcdet.egg-info/requires.txt
354.0         writing top-level names to pcdet.egg-info/top_level.txt
354.0         writing manifest file 'pcdet.egg-info/SOURCES.txt'
354.0         reading manifest file 'pcdet.egg-info/SOURCES.txt'
354.0         writing manifest file 'pcdet.egg-info/SOURCES.txt'
354.0         running build_ext
354.0         building 'pcdet.ops.iou3d_nms.iou3d_nms_cuda' extension
354.0         creating /app/build/temp.linux-x86_64-cpython-38/pcdet/ops/iou3d_nms/src
354.0         No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
354.0         /usr/local/lib/python3.8/dist-packages/setuptools/dist.py:337: InformationOnly: Normalizing '0.6.0+0000000' to '0.6.0+0'
354.0           self.metadata.version = self._normalize_version(self.metadata.version)
354.0         /usr/local/lib/python3.8/dist-packages/setuptools/command/develop.py:41: EasyInstallDeprecationWarning: easy_install command is deprecated.
354.0         !!
354.0
354.0                 ********************************************************************************
354.0                 Please avoid running ``setup.py`` and ``easy_install``.
354.0                 Instead, use pypa/build, pypa/installer or other
354.0                 standards-based tools.
354.0
354.0                 See https://github.com/pypa/setuptools/issues/917 for details.
354.0                 ********************************************************************************
354.0
354.0         !!
354.0           easy_install.initialize_options(self)
354.0         /usr/local/lib/python3.8/dist-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.   
354.0         !!
354.0
354.0                 ********************************************************************************
354.0                 Please avoid running ``setup.py`` directly.
354.0                 Instead, use pypa/build, pypa/installer or other
354.0                 standards-based tools.
354.0
354.0                 See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
354.0                 ********************************************************************************
354.0
354.0         !!
354.0           self.initialize_options()
354.0         Traceback (most recent call last):
354.0           File "<string>", line 2, in <module>
354.0           File "<pip-setuptools-caller>", line 34, in <module>
354.0           File "/app/setup.py", line 34, in <module>
354.0             setup(
354.0           File "/usr/local/lib/python3.8/dist-packages/setuptools/__init__.py", line 117, in setup
354.0             return distutils.core.setup(**attrs)
354.0           File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/core.py", line 183, in setup
354.0             return run_commands(dist)
354.0           File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/core.py", line 199, in run_commands
354.0             dist.run_commands()
354.0           File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 954, in run_commands
354.0             self.run_command(cmd)
354.0           File "/usr/local/lib/python3.8/dist-packages/setuptools/dist.py", line 999, in run_command
354.0             super().run_command(command)
354.0           File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 973, in run_command
354.0             cmd_obj.run()
354.0           File "/usr/local/lib/python3.8/dist-packages/setuptools/command/develop.py", line 35, in run
354.0             self.install_for_development()
354.0           File "/usr/local/lib/python3.8/dist-packages/setuptools/command/develop.py", line 112, in install_for_development
354.0             self.run_command('build_ext')
354.0           File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/cmd.py", line 316, in run_command
354.0             self.distribution.run_command(command)
354.0           File "/usr/local/lib/python3.8/dist-packages/setuptools/dist.py", line 999, in run_command
354.0             super().run_command(command)
354.0           File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 973, in run_command
354.0             cmd_obj.run()
354.0           File "/usr/local/lib/python3.8/dist-packages/setuptools/command/build_ext.py", line 98, in run
354.0             _build_ext.run(self)
354.0           File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
354.0             self.build_extensions()
354.0           File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
354.0             build_ext.build_extensions(self)
354.0           File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
354.0             self._build_extensions_serial()
354.0           File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial       
354.0             self.build_extension(ext)
354.0           File "/usr/local/lib/python3.8/dist-packages/setuptools/command/build_ext.py", line 263, in build_extension
354.0             _build_ext.build_extension(self, ext)
354.0           File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/command/build_ext.py", line 557, in build_extension
354.0             objects = self.compiler.compile(
354.0           File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 649, in unix_wrap_ninja_compile
354.0             cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
354.0           File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 548, in unix_cuda_flags
354.0             cflags + _get_cuda_arch_flags(cflags))
354.0           File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1793, in _get_cuda_arch_flags
354.0             raise ValueError(f"Unknown CUDA arch ({arch}) or GPU not supported")
354.0         ValueError: Unknown CUDA arch (8.9) or GPU not supported
354.0         [end of output]
354.0
354.0     note: This error originates from a subprocess, and is likely not a problem with pip.
354.0 error: subprocess-exited-with-error
354.0
354.0 × python setup.py develop did not run successfully.
354.0 │ exit code: 1
354.0 ╰─> [90 lines of output]
354.0     running develop
354.0     running egg_info
354.0     creating pcdet.egg-info
354.0     writing pcdet.egg-info/PKG-INFO
354.0     writing dependency_links to pcdet.egg-info/dependency_links.txt
354.0     writing requirements to pcdet.egg-info/requires.txt
354.0     writing top-level names to pcdet.egg-info/top_level.txt
354.0     writing manifest file 'pcdet.egg-info/SOURCES.txt'
354.0     reading manifest file 'pcdet.egg-info/SOURCES.txt'
354.0     writing manifest file 'pcdet.egg-info/SOURCES.txt'
354.0     running build_ext
354.0     building 'pcdet.ops.iou3d_nms.iou3d_nms_cuda' extension
354.0     creating /app/build/temp.linux-x86_64-cpython-38/pcdet/ops/iou3d_nms/src
354.0     No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
354.0     /usr/local/lib/python3.8/dist-packages/setuptools/dist.py:337: InformationOnly: Normalizing '0.6.0+0000000' to '0.6.0+0'
354.0       self.metadata.version = self._normalize_version(self.metadata.version)
354.0     /usr/local/lib/python3.8/dist-packages/setuptools/command/develop.py:41: EasyInstallDeprecationWarning: easy_install command is deprecated. 
354.0     !!
354.0
354.0             ********************************************************************************
354.0             Please avoid running ``setup.py`` and ``easy_install``.
354.0             Instead, use pypa/build, pypa/installer or other
354.0             standards-based tools.
354.0
354.0             See https://github.com/pypa/setuptools/issues/917 for details.
354.0             ********************************************************************************
354.0
354.0     !!
354.0       easy_install.initialize_options(self)
354.0     /usr/local/lib/python3.8/dist-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.       
354.0     !!
354.0
354.0             ********************************************************************************
354.0             Please avoid running ``setup.py`` directly.
354.0             Instead, use pypa/build, pypa/installer or other
354.0             standards-based tools.
354.0
354.0             See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
354.0             ********************************************************************************
354.0
354.0     !!
354.0       self.initialize_options()
354.0     Traceback (most recent call last):
354.0       File "<string>", line 2, in <module>
354.0       File "<pip-setuptools-caller>", line 34, in <module>
354.0       File "/app/setup.py", line 34, in <module>
354.0         setup(
354.0       File "/usr/local/lib/python3.8/dist-packages/setuptools/__init__.py", line 117, in setup
354.0         return distutils.core.setup(**attrs)
354.0       File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/core.py", line 183, in setup
354.0         return run_commands(dist)
354.0       File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/core.py", line 199, in run_commands
354.0         dist.run_commands()
354.0       File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 954, in run_commands
354.0         self.run_command(cmd)
354.0       File "/usr/local/lib/python3.8/dist-packages/setuptools/dist.py", line 999, in run_command
354.0         super().run_command(command)
354.0       File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 973, in run_command
354.0         cmd_obj.run()
354.0       File "/usr/local/lib/python3.8/dist-packages/setuptools/command/develop.py", line 35, in run
354.0         self.install_for_development()
354.0       File "/usr/local/lib/python3.8/dist-packages/setuptools/command/develop.py", line 112, in install_for_development
354.0         self.run_command('build_ext')
354.0       File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/cmd.py", line 316, in run_command
354.0         self.distribution.run_command(command)
354.0       File "/usr/local/lib/python3.8/dist-packages/setuptools/dist.py", line 999, in run_command
354.0         super().run_command(command)
354.0       File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 973, in run_command
354.0         cmd_obj.run()
354.0       File "/usr/local/lib/python3.8/dist-packages/setuptools/command/build_ext.py", line 98, in run
354.0         _build_ext.run(self)
354.0       File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
354.0         self.build_extensions()
354.0       File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
354.0         build_ext.build_extensions(self)
354.0       File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
354.0         self._build_extensions_serial()
354.0       File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
354.0         self.build_extension(ext)
354.0       File "/usr/local/lib/python3.8/dist-packages/setuptools/command/build_ext.py", line 263, in build_extension
354.0         _build_ext.build_extension(self, ext)
354.0       File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/command/build_ext.py", line 557, in build_extension
354.0         objects = self.compiler.compile(
354.0       File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 649, in unix_wrap_ninja_compile
354.0         cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
354.0       File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 548, in unix_cuda_flags
354.0         cflags + _get_cuda_arch_flags(cflags))
354.0       File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1793, in _get_cuda_arch_flags
354.0         raise ValueError(f"Unknown CUDA arch ({arch}) or GPU not supported")
354.0     ValueError: Unknown CUDA arch (8.9) or GPU not supported
354.0     [end of output]
354.0
354.0 note: This error originates from a subprocess, and is likely not a problem with pip.
------

 1 warning found (use docker --debug to expand):
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 4)
Dockerfile:34
--------------------
  32 |     COPY ./requirements.txt ./
  33 |     COPY ./setup.py ./
  34 | >>> RUN pip install -e . --ignore-installed
  35 |
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install -e . --ignore-installed" did not complete successfully: exit code: 1

View build details: docker-desktop://dashboard/build/default/default/ot6b8kf8778x07w15zuzfyyto
Failed to deploy '<unknown> Dockerfile: base_image/Dockerfile': Image build failed with exit code 1.
` 大佬你遇到这个错了吗

**Comment by Creating-ZXY** [comment]
> > 您好，请问您解决了吗
> 
> `解决了，看这个基础dockerfile，下面内容可能有高亮错误，对比原来的文件更新吧
> 
> # 使用 CUDA 11.7.1 的基础镜像
> FROM nvcr.io/nvidia/cuda:11.7.1-cudnn8-devel-ubuntu20.04
> 
> USER root ENV DEBIAN_FRONTEND noninteractive
> 
> # 设置pip源为阿里云源
> # ENV PIP_INDEX_URL=https://mirrors.aliyun.com/pypi/simple/
> ENV PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
> 
> # # 添加 NVIDIA apt 公钥
> # RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub \
> # && apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/7fa2af80.pub
> # 更新 apt 并安装基本工具
> RUN apt-get clean && apt-get update && apt-get install -y apt-utils ca-certificates git wget sudo vim net-tools
> 
> # 安装 Python 及其依赖
> # install python
> RUN apt-get install -y libffi-dev libjpeg-dev zlib1g-dev libssl-dev python3-dev python3-pip && ln -svf /usr/bin/python3 /usr/bin/python && ln -svf /usr/bin/pip3 /usr/bin/pip && pip install --upgrade pip
> 
> # 安装 PyTorch，指定适配 CUDA 11.7 的版本
> # install PyTorch
> RUN pip install Pillow==6.2
> 
> # # 将本地的 third_libs 目录复制到 Docker 镜像中的 /third_libs 目录
> COPY ./third_libs /third_libs
> 
> RUN pip install /third_libs/torch-1.13.1+cu117-cp38-cp38-linux_x86_64.whl && rm -rf /third_libs
> 
> RUN pip install torchvision==0.14.1+cu117 torchaudio==0.13.1 -f https://download.pytorch.org/whl/torch_stable.html
> 
> # install spconv
> RUN pip install spconv-cu113
> 
> WORKDIR /app
> 
> # install pcdet
> ENV TORCH_CUDA_ARCH_LIST="5.0 5.2 6.0 6.1 7.0 7.5 8.6+PTX"
> 
> # COPY . ./
> COPY ./pcdet ./pcdet/ COPY ./requirements.txt ./ COPY ./setup.py ./
> 
> # 以下安装方式会有警告，先不管
> RUN pip install -e .

您好，谢谢您指导。目前我已经重新构建了镜像。但是在启动point-cloud-object-detection镜像的时候报错了`==========
== CUDA ==
==========

CUDA Version 11.7.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

Traceback (most recent call last):
  File "app.py", line 2, in <module>
    from pcdet_open.service import *
ModuleNotFoundError: No module named 'pcdet_open'
`请问您有遇到吗？

**Comment by Creating-ZXY** [comment]
> > 您好，请问您解决了吗
> 
> `解决了，看这个基础dockerfile，下面内容可能有高亮错误，对比原来的文件更新吧
> 
> # 使用 CUDA 11.7.1 的基础镜像
> FROM nvcr.io/nvidia/cuda:11.7.1-cudnn8-devel-ubuntu20.04
> 
> USER root
> ENV DEBIAN_FRONTEND noninteractive
> 
> # 设置pip源为阿里云源
> # ENV PIP_INDEX_URL=https://mirrors.aliyun.com/pypi/simple/
> ENV PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
> 
> # # 添加 NVIDIA apt 公钥
> # RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub \
> #     && apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/7fa2af80.pub
> 
> # 更新 apt 并安装基本工具
> RUN apt-get clean && apt-get update \
>     && apt-get install -y apt-utils ca-certificates git wget sudo vim net-tools 
> 
> # 安装 Python 及其依赖
> # install python
> RUN apt-get install -y libffi-dev libjpeg-dev zlib1g-dev libssl-dev python3-dev python3-pip \
>     && ln -svf /usr/bin/python3 /usr/bin/python \
>     && ln -svf /usr/bin/pip3 /usr/bin/pip \
>     && pip install --upgrade pip
> 
> # 安装 PyTorch，指定适配 CUDA 11.7 的版本
> # install PyTorch
> RUN pip install Pillow==6.2
> 
> # # 将本地的 third_libs 目录复制到 Docker 镜像中的 /third_libs 目录
> COPY ./third_libs /third_libs
> 
> RUN pip install /third_libs/torch-1.13.1+cu117-cp38-cp38-linux_x86_64.whl \
>     && rm -rf /third_libs
> 
> RUN pip install torchvision==0.14.1+cu117 torchaudio==0.13.1 -f https://download.pytorch.org/whl/torch_stable.html
> 
> # install spconv
> RUN pip install spconv-cu113
> 
> WORKDIR /app
> 
> # install pcdet
> ENV TORCH_CUDA_ARCH_LIST="5.0 5.2 6.0 6.1 7.0 7.5 8.6+PTX"
> # COPY . ./
> COPY ./pcdet ./pcdet/
> COPY ./requirements.txt ./
> COPY ./setup.py ./
> # 以下安装方式会有警告，先不管
> RUN pip install -e .
> 
> 
> 
> 

目前成功编译。
还想请问一下您尝试换过它的模型吗？

**Comment by chenjian88888** [comment]
> > > 您好，请问您解决了吗
> > 
> > 
> > `解决了，看这个基础dockerfile，下面内容可能有高亮错误，对比原来的文件更新吧
> > # 使用 CUDA 11.7.1 的基础镜像
> > FROM nvcr.io/nvidia/cuda:11.7.1-cudnn8-devel-ubuntu20.04
> > USER root
> > ENV DEBIAN_FRONTEND noninteractive
> > # 设置pip源为阿里云源
> > # ENV PIP_INDEX_URL=https://mirrors.aliyun.com/pypi/simple/
> > ENV PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
> > # # 添加 NVIDIA apt 公钥
> > # RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub \
> > # && apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/7fa2af80.pub
> > # 更新 apt 并安装基本工具
> > RUN apt-get clean && apt-get update 
> > && apt-get install -y apt-utils ca-certificates git wget sudo vim net-tools
> > # 安装 Python 及其依赖
> > # install python
> > RUN apt-get install -y libffi-dev libjpeg-dev zlib1g-dev libssl-dev python3-dev python3-pip 
> > && ln -svf /usr/bin/python3 /usr/bin/python 
> > && ln -svf /usr/bin/pip3 /usr/bin/pip 
> > && pip install --upgrade pip
> > # 安装 PyTorch，指定适配 CUDA 11.7 的版本
> > # install PyTorch
> > RUN pip install Pillow==6.2
> > # # 将本地的 third_libs 目录复制到 Docker 镜像中的 /third_libs 目录
> > COPY ./third_libs /third_libs
> > RUN pip install /third_libs/torch-1.13.1+cu117-cp38-cp38-linux_x86_64.whl 
> > && rm -rf /third_libs
> > RUN pip install torchvision==0.14.1+cu117 torchaudio==0.13.1 -f https://download.pytorch.org/whl/torch_stable.html
> > # install spconv
> > RUN pip install spconv-cu113
> > WORKDIR /app
> > # install pcdet
> > ENV TORCH_CUDA_ARCH_LIST="5.0 5.2 6.0 6.1 7.0 7.5 8.6+PTX"
> > # COPY . ./
> > COPY ./pcdet ./pcdet/
> > COPY ./requirements.txt ./
> > COPY ./setup.py ./
> > # 以下安装方式会有警告，先不管
> > RUN pip install -e .
> 
> 目前成功编译。 还想请问一下您尝试换过它的模型吗？


你可以看下pcdet_open这个文件夹的代码，将它移植进入你的检测模型中，就可以实现AI辅助编译，不用他原来的架构
